@isTest
public class CustomerDetailsTempTest {

    static testMethod void testOldCustomerDetailsWSDL() {
        
		new CustomerDetailsWSUtil.WexGeneralFault_element();
		new CustomerDetailsWSUtil.accountSearchResponse();
		new CustomerDetailsWSUtil.Address();
		new CustomerDetailsWSUtil.accountSearchRequest();
		new CustomerDetailsWSUtil.customerDetailsRequest();
		new CustomerDetailsWSUtil.getRecentDeclinedAuthsRequest();
		new CustomerDetailsWSUtil.authLogRecord();
		new CustomerDetailsWSUtil.dataTableAuthLogRecord();
		new CustomerDetailsWSUtil.authSearchResult();
		new CustomerDetailsWSUtil.getRecentDeclinedAuthsResponse();
		new CustomerDetailsWSUtil.AccountSearchDTO();
		new CustomerDetailsWSUtil.updateSalesforceID();
		new CustomerDetailsWSUtil.AbstractContact();
		new CustomerDetailsWSUtil.getContactsResponse();
		new CustomerDetailsWSUtil.accountSearch();
		new CustomerDetailsWSUtil.getContacts();
		new CustomerDetailsWSUtil.Contact();
		new CustomerDetailsWSUtil.getAgingHistory();
		new CustomerDetailsWSUtil.getCustomerDetailsResponse();
		new CustomerDetailsWSUtil.getAgingHistoryResponse();
		new CustomerDetailsWSUtil.Contacts();
		new CustomerDetailsWSUtil.agingHistory();
		new CustomerDetailsWSUtil.getCustomerDetails();
		new CustomerDetailsWSUtil.customerDetails();
		new CustomerDetailsWSUtil.updateSalesforceIDResponse();
		new CustomerDetailsWSUtil.accountSearchResult();
		new CustomerDetailsWSUtil.CustomerDetailsSOAPQSPort();
        
    }
    
}