public class WEXCTIUtil_FinesseNotification {
    /*public data data{get;set;}
    public String source{get;set;}
    public String requestId{get;set;}
    public String SearchDisposition{get;set;}
    public String event{get;set;}
    public class participants{
        public list<Participant> Participant{get;set;}
    }
    public class Participant{
        public String mediaAddressType{get;set;}
        public String mediaAddress{get;set;}
        public String startTime{get;set;}
        public String state{get;set;}
        public String stateCause{get;set;}
        public String stateChangeTime{get;set;}
    }
    public class mediaProperties{
        public String dialedNumber{get;set;}
        public String outboundClassification{get;set;}
        public String callType{get;set;}
        public callvariables callvariables{get;set;}
        public String DNIS{get;set;}
    }
    public class dialogs{
        public Dialog Dialog{get;set;}
    }
    public class Dialog{
        public String mediaType{get;set;}
        public mediaProperties mediaProperties{get;set;}
        public String state{get;set;}
        public participants participants{get;set;}
        public String toAddress{get;set;}
        public String id{get;set;}
        public String uri{get;set;}
        public String fromAddress{get;set;}
        public String associatedDialogUri{get;set;}
    }
    public class data{
        public dialogs dialogs{get;set;}
    }
    public class callvariables{
        public list<CallVariable> CallVariable{get;set;}
    }
    public class CallVariable{
        public String value{get;set;}
        public String name{get;set;}
    }*/
}