/* This class is used by the CreditApplication (BOCA) process.  */
public class WEXErrorUtility {
//    public static String INVALID_PROGRAM = 'InvalidProgram';
//    public static String UNPUBLISHED = 'UnPublished';
//    public static String NO_TNCS = 'NoTNCs';
//    public static String INVALID_TEMPLATE = 'The specified template in the url is not defined for the program.';
//
//	public static Map<String, String> errorMap = new Map<String, String>();
//
//    public static String getErrorMessage(String key){
//
//        setErrorMessageMap();
//        return errorMap.get(key);
//
//    }
//    
//    private static void setErrorMessageMap(){
//        errorMap.put(INVALID_PROGRAM, 'An invalid program is in the URL');
//        errorMap.put(UNPUBLISHED, 'The programs BOCA you are trying to apply for isnt ready for prime time yet (unpublished)');
//        errorMap.put(NO_TNCS, 'There are no T & Cs defined for that program..');
//    }
}