@isTest
private class AccountAssetcStatsTriggerTest {
//
//   static testMethod void testTrigger() {
//      //try {
//
//          Account a = new Account();
//          a.name = 'test';
//          insert a;
//
//          Account_Asset__c o = new Account_Asset__c();
//          o.account__c = a.id;
//          insert o;
//
//          System.assertNotEquals(null, o);
//      //}
//      //catch(Exception e) {
//       //   List<Account_Asset__c> l = [SELECT Id from Account_Asset__c LIMIT 1];
//        //  update l;
//         // System.assertNotEquals(null, l);
//      //}
//   }
}