@isTest
private class CampaignProgramcStatsTriggerTest {

   static testMethod void testTrigger() {
      try {
          Campaign_Program__c o = new Campaign_Program__c();
          insert o;

          System.assertNotEquals(null, o);
      }
      catch(Exception e) {
          List<Campaign_Program__c> l = [SELECT Id from Campaign_Program__c LIMIT 1];
          update l;
          System.assertNotEquals(null, l);
      }
   }
}