public with sharing class OpportunityUtility {
 
//    public static void removeCarriageReturnsFromOpty(Opportunity[] optys){
//       	List<String> badValues = new String[]{'\r','\n'};
//        String newVal = '  ';
//
//        for (Opportunity opty:optys){
//           opty.Billing_Street__c = WEXHelper.replaceChar((String)opty.Billing_Street__c, badValues,newVal );
//           opty.Billing_Street_Line_2__c = WEXHelper.replaceChar((String)opty.Billing_Street__c, badValues,newVal );
//
//           opty.Physical_Street__c = WEXHelper.replaceChar((String)opty.Physical_Street__c, badValues ,newVal );
//           opty.Physical_Street_Line_2__c = WEXHelper.replaceChar((String)opty.Physical_Street_Line_2__c, badValues ,newVal );
//
//           opty.Guarantor_address_line_1__c = WEXHelper.replaceChar((String)opty.Guarantor_address_line_1__c, badValues ,newVal );
//           opty.Guarantor_address_line_2__c = WEXHelper.replaceChar((String)opty.Guarantor_address_line_2__c, badValues ,newVal );
//
//           //the following one can't be fixed right now. Its a formula field off the contact object.
//           //opty.Primary_Contact_Street_Address__c = WEXHelper.replaceChar((String)opty.Primary_Contact_Street_Address__c, badVal ,newVal );
//           opty.Primary_Contact_Street_Address_Line_2__c = WEXHelper.replaceChar((String)opty.Primary_Contact_Street_Address_Line_2__c, badValues,newVal);
//
//        }
//    }
       
}