/***************************************************************************************************
* Created By : PRM | Cloud Solutions
* Purpose : Test class to test CardDetailAssociation trigger
* Date of Creation : 24-July-2013

* 23-May-2014 Manu Erwin (Salesforce.com) DELETE THIS CLASS
****************************************************************************************************/

@isTest
private class TestCardDetailAssociationTrg{}