@isTest
private class Test_Announcements {
	
//	public static testMethod void testAnnouncements() {
//
//        Announcements__c naa = new Announcements__c();
//        naa.Active__c = true;
//        naa.Date_Posted__c = Date.today();
//        naa.End_Date__c = Date.today().addDays(7);
//        naa.Name = 'Test News';
//        naa.Summary__c = 'Some news';
//        naa.URL__c = 'http://www.google.com';
//        naa.OwnerId = System.UserInfo.getUserId();
//        insert naa;
//
//        AnnouncementsController controller = new AnnouncementsController();
//        controller.NumberOfAnnouncements = 5;
//
//        PageReference pageRef = Page.Announcements;
//        Test.setCurrentPage(pageRef);
//
//        List<AnnouncementsController.announcmentWrapper> anns = controller.Records;
//    }
	
}