@IsTest
public class TestUpdateCoupon{
    
//    static testmethod void insertCampaignPricing(){
//
//        Campaign testCampaign = new Campaign();
//
//        testCampaign.Name = 'TestCampaign';
//        testCampaign.Coupon_Code__c = 'FFF';
//        testCampaign.IsActive = true;
//
//        insert testCampaign;
//
//        Campaign_Pricing__c cmp= new Campaign_Pricing__c();
//
//        cmp.Name = 'TestCampaignPricing';
//        cmp.coup_code__c = 'FFF';
//
//        insert cmp;
//
//        Campaign_Pricing__c cmpInActive = new Campaign_Pricing__c();
//
//        cmpInActive.Name = 'TestCampaignPricing';
//        cmpInActive.coup_code__c = 'FAA';
//
//        insert cmpInActive;
//
//    }

}