//NOTE: commenting out per code rewrite

@isTest
private class V2SA_Test_CreateCampaignMemberLeadUpload  {

    static testMethod void verifyV2SA_CreateCampaignMemberLeadUploadTrigger(){
    
    
  
    /*

    test.startTest();
    Campaign cam = new Campaign(Name = 'test c', Type='Acquire', Coupon_Code__c='05', status='planned', drop_date__c=date.today());
    insert cam;
    
    
    
    lead lea = new lead(LastName = 'lead 1', SFcampaign_id__c = cam.id, Company='test', Status='untouched', LeadSource ='Advertisement', Primary_Campaign__c=cam.Id);
    insert lea;    
    
    lead lea2 = new lead(LastName = 'lead 1', SFcampaign_id__c = cam.id, Company='test', Status='untouched', LeadSource ='Advertisement', Primary_Campaign__c=null);
    insert lea2;
    
    lead lea3 = new lead(LastName = 'lead 1', SFcampaign_id__c = null, Company='test', Status='untouched', LeadSource ='Advertisement', Primary_Campaign__c= cam.id);
    insert lea3;
    
    CampaignMember campmem = new CampaignMember(leadid=lea.id, campaignid=cam.id);
    insert campmem;
    
    test.stopTest();

    lead updatelead =   [select primary_campaign__c, SFCampaign_id__c from lead where id = :lea2.id];
    system.assertequals(lea.primary_campaign__r.id, lea2.primary_campaign__r.id);
    
    */    

          
    }
}