body{
    font-family: arial;
    height: 100%;
    width: 100%;
    margin: 0;
    padding: 0;
    background-color: #7f7f7f;
    
    
}
html {
    height: 100%;
    width: 100%;
    margin: 0;
    padding: 0;
}
#page{
    background-color:white;
}
header{
    margin: 0 auto;
    width: 100%;
    min-height: 100px;
    padding-top: 10px;
background: #0a0a0a; /* Old browsers */
/* IE9 SVG, needs conditional override of 'filter' to 'none' */
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzBhMGEwYSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjIwJSIgc3RvcC1jb2xvcj0iIzExMTExMSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjQxJSIgc3RvcC1jb2xvcj0iIzExMTExMSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiM3YzdjN2MiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
background: -moz-linear-gradient(top,  #0a0a0a 0%, #111111 20%, #111111 41%, #7c7c7c 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#0a0a0a), color-stop(20%,#111111), color-stop(41%,#111111), color-stop(100%,#7c7c7c)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  #0a0a0a 0%,#111111 20%,#111111 41%,#7c7c7c 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  #0a0a0a 0%,#111111 20%,#111111 41%,#7c7c7c 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  #0a0a0a 0%,#111111 20%,#111111 41%,#7c7c7c 100%); /* IE10+ */
background: linear-gradient(to bottom,  #0a0a0a 0%,#111111 20%,#111111 41%,#7c7c7c 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#0a0a0a', endColorstr='#7c7c7c',GradientType=0 ); /* IE6-8 */

}
#arrCol,#arrChart,#depCol,#depChart{
    margin: 0px 0px 0px 0px;
    background-color:none;
}
.wrapper{
    margin-bottom: 4%;
}
header h1{
    padding: 12px 0px 0px 40px;
    margin: 0px;
    font-weight: bold;
    color: #fff;
    font-size: 24px;
}
header h2{
    padding: 2px 0px 0px 40px;
    margin: 0px;
    font-weight: bold;
    color: #fff;
    font-size: 18px;
}

.wex_logo{
    max-width: 90px;
    background-size: 82%;
    float: left;
    padding: 0px 0px 0px 10px;
    margin: 0px;
}
.emailHeader{
    height: 90px;
    width:100%;
    background-color:#262626;
    margin: 0px;
}
.emailHeader h3{
    margin-left:0px;
    color: white;
    -webkit-transform: scale(1, 1.1);
    letter-spacing: 1px;
    padding-top:20px;
}
.h3.reg{
    display:inline;
    float:right;
    padding-left:5px;
    margin-top:100px;
    
}
#regBox{
   margin-left:10%;
   padding-left: 5%;
   width: 120px;  
   border-top: 1px solid #fcc436;
   background: #d6a228;
   background: -webkit-gradient(linear, left top, left bottom, from(#fcc436), to(#d6a228));
   background: -webkit-linear-gradient(top, #fcc436, #d6a228);
   background: -moz-linear-gradient(top, #fcc436, #d6a228);
   background: -ms-linear-gradient(top, #fcc436, #d6a228);
   background: -o-linear-gradient(top, #fcc436, #d6a228);
   padding: 5px 10px;
   -webkit-border-radius: 8px;
   -moz-border-radius: 8px;
   border-radius: 8px;
   -webkit-box-shadow: rgba(0,0,0,1) 0 1px 0;
   -moz-box-shadow: rgba(0,0,0,1) 0 1px 0;
   box-shadow: rgba(0,0,0,1) 0 1px 0;
   text-shadow: rgba(0,0,0,.4) 0 1px 0;
   color: white;
   font-size: 14px;
   font-family: Georgia, serif;
   text-decoration: none;
   vertical-align: middle;
   }
#regBox:hover {
   border-top-color: #fcc436;
   background: #fcc436;
   color: #ffffff;
   }
#regBox:active {
   border-top-color: #fcc436;
   background: #fcc436;
   }
    
.formArea{
    margin:0 auto;
    width:90%;
    padding: 5px 0px 10px 20px;
    background-color:white;
    border-top: 2px solid #747E96;
    /*background-color:#F8F8F8;*/
}
.input{
    width:100%;
    max-width:300px;
    border-bottom: 1px solid #ECECEC ;
    
}
.message{
    border:2px solid #262626;
    border-radius: 0px;
    background-color: white;
    display:block;
    width:85%;
    padding: 0px;
    margin: 0 auto;       
}
p.message, form.message{
    padding: 5px 0px 10px 20px;
    
}
a.popoverOption:hover{
    color:inherit;
    text-decoration:none;
}
.update{
    padding-left:20px;
}
.emailInfo{
    border-top: 2px solid #747E96;
    width:90%;
    background-color: white;
    margin:0 auto;
    padding:5px 0px 0px 20px;
}
.emailWrapper{ 
    background-color: #F8F8F8;
    margin:0 auto;
    width:90%;
    height:100%;
    padding-top:10px;
    
}
.inputHeader h1{
    font-size:20px;
    
}

/*#feed for next sprints when Attendee will have sidebar features for travel, etc.{*/
/*background: url("images/download%20(4).png") no-repeat 90% ;*/
/*margin-left: 20%;*/
/*width: 1030px;*/
/*height: 649px;*/
/*padding: 10px 0px 0px 10px ;*/
/*border-left: 1px #2f2f2f solid;*/

/*}*/

#travel{
    margin-bottom:30px;
}
.inputArea{
    width:100%;
    display:block;
    padding: 10px 0px 0px 10px;
}
.inputButton{
    margin-top:25px;
    min-width:40px;
    max-width:150px;
    display:block;
}
.odd {
   background: #ccc;
}
body .pbBody table.list tr.dataRow th, body .pbBody table.list tr.dataRow td{
    vertical-align:top;
}

.feedpage .zen{
    width:80%;
}
.feedmain{
    width:70%;
}
.feedmainandrightbar{
    width:80%;
}
.zen-pts{
    
}
@media (max-width: 600px){
.feedmainandrightbar{
    width:40%;
}
  #travel{
    margin-bottom:3px;
}
.inputArea{
    width:80%;
    display:block;
    padding: 3px 0px 0px 3px;
}
.inputButton{
    margin-top:5px;
    min-width:20px;
    max-width:150px;
    display:block;
}

/*Graph Styling*/
#map {
    font-family: Arial;
    font-size:12px;
    line-height:normal !important;
    width:80%;
    height:80%;
    position:relative;
    background:transparent;
}

.feedpage .zen{
    width:80%;
}
.feedmain{
    width:70%;
}
.feedmainandrightbar{
    width:80%;
}

    header h1{
    padding-left:2%;
    margin: 0px;
    font-weight: bold;
    color: #fff;
    font-size: 1.5em;
}
header h2{
    padding-left: 2%;
    margin: 0px;
    font-weight: bold;
    color: #fff;
    font-size: 1em;
}

.wex_logo{
    max-width: 90px;
    background-size: 82%;
    float: left;
    padding: 0px 0px 0px 5px;
    margin: 0px;
}

 #followButton{
        width: 200px;
        display:inline;
        float:right;
    }
    
