ID,SALES_STAGE__C,OPPORTUNITY__C,SIEBEL_OPPTY__C,APPLICATION_STAGE__C,STATUS__C,COMPLIANCE_DECISION__C
a0V180000016mO4EAI,04 - Application Received,0066C000005chKeQAI,,Adjudication,Pending Decision,Declined
a0V180000016mPKEAY,04 - Application Received,00618000009d3nFAAQ,,Adjudication,Pending Decision,Declined
a0V5C000000gZdpUAE,04 - Application Received,0065C000004jwHkQAI,Test,Adjudication,Pending Decision,Declined