ID,CURRENCYISOCODE,Platform__c,User_Operator_ID__c,User_Authority_Limit__c,Non_User_Email_Address__c,Non_User_Full_Name__c,Non_User_Manager__c,Non_User_Manager_Email_ID__c
aBd0g0000008OA1CAM,USD,EFSTS,pclemens@efsllc,15000,baim_ron@yahoo.com,Annalisa Girardi,Marilee Wishon,manager_baim_ron@yahoo.com
aBd0g0000008OA2CAM,USD,EFSTS,dsmith@efsllc,50000,yuanito.kurniawan@sea.ccamatil.com,Sona Cauthen,Margene Stehle,manager_yuanito.kurniawan@sea.ccamatil.com
aBd0g0000008OA3CAM,USD,EFSTS,aschneid@efsllc,15000,cianjur@indo.net.id,Clarissa Danker,Nathalie Branner,manager_cianjur@indo.net.id
aBd0g0000008OA4CAM,USD,EFSTS,bking@efsllc,50000,kawasspa@indosat.net.id,Patti Heth,Lory Degnan,manager_kawasspa@indosat.net.id
aBd0g0000008OA5CAM,USD,EFSTS,bchristensen@efsllc,15000,hatoe7@yahoo.co.jp,Gracie Kindig,Nicol Stotler,manager_hatoe7@yahoo.co.jp
aBd0g0000008OA6CAM,USD,EFSTS,awhite@efsllc,15000,chakra_92@yahoo.com,Kristen Kenton,Keva Schuetz,manager_chakra_92@yahoo.com
aBd0g0000008OA7CAM,USD,NATC,chimm,15000,pamilu@mas-travel.com,Nancie Stacks,Hanh Reyes,manager_pamilu@mas-travel.com
aBd0g0000008OA8CAM,USD,NATC,Cprevedel,15000,gus_war81@yahoo.com,Ginny Plowman,Cecila Sperling,manager_gus_war81@yahoo.com
aBd0g0000008OA9CAM,USD,NATC,Vcanita,100000,kf034@indosat.net.id,Alleen Godina,Tristan Topping,manager_kf034@indosat.net.id
aBd0g0000008OB1CAM,USD,NATC,Ecorrea,50000,rido@weddingku.com,Delores Mcfatridge,Joni Macy,manager_rido@weddingku.com
